//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractToUser
    {
        public int contractCode { get; set; }
        public string userId { get; set; }
        public double accumulatedAmount { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual ContractTravel ContractTravel { get; set; }
    }
}
